services:
  neuro_al:
    build:
      context: .
    volumes:
      - ./src:/neuro_al
      - ${VOLUME_CLEVR}:/mnt/CLEVR
      - ${VOLUME_CLEVR_HANS}:/mnt/CLEVR_Hans
    stdin_open: true
    tty: true